config/routes.rb
Rails.application.routes.draw do

  resources :kittens

  root "kittens#index"

end

app/models/kitten.rb
class Kitten < ActiveRecord::Base

  validates :name,     presence: true, length: { maximum: 50 }
  validates :age,      presence: true
  validates :cuteness, presence: true
  validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "New kitten created! =^.^="
      redirect_to @kitten
    else
      render 'new'
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update_attributes(kitten_params)
      flash[:success] = "Kitten updated! =^.^="
      redirect_to @kitten
    else
      render 'edit'
    end
  end

  def index
    @kittens = Kitten.all.paginate(page: params[:page])
    respond_to do |format|
      format.html #index.html.erb
      format.xml  { render xml:  @kittens}
      format.json { render json: @kittens}
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html #index.html.erb
      format.xml  { render xml:  @kitten}
      format.json { render json: @kitten}
    end
    @title  = @kitten.name
  end

  def destroy
    @kitten = Kitten.find(params[:id]).destroy
    flash[:success] = "Kitten removed from database. Mrrow"
    redirect_to root_url
  end

  private

    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '') # cribbed from Rails Tutorial by Michael Hartl
    default_title = "Kitten Kreator"
    if page_title.empty?
      default_title
    else
      page_title + " | " + default_title
    end
  end
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<br>
<%= form_for(@kitten) do |f| %>
  <ul>
    <%= f.label "Name: " %>
    <%= f.text_field :name %>
  </ul>
  <ul>
    <%= f.label "Age (in months): " %>
    <%= f.select :age, options_for_select(6.downto(1)) %>
  </ul>>
  <ul>
    <%= f.label "Cuteness factor: " %>
    <%= f.select :cuteness, options_for_select(10.downto(1)) %>
  </ul>
  <ul>
    <%= f.label "Softness factor: " %>
    <%= f.select :softness, options_for_select(10.downto(1)) %>
  </ul>
  <ul>
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  </ul>
<% end %>

app/views/kittens/edit.html.erb
<% provide(:title, "Change kitten parameters") %>
<% provide(:button_text, "Kitten updated!") %>

<ul><h3>Change kitteh parameters</h3></ul>
<%= render 'form' %>

<ul>
  <%= link_to "delete this cuddler (u monster)", @kitten, method: :delete,
      data: { confirm: "Sure you want to delete this precious meeper?" } %>
</ul>

app/views/kittens/index.html.erb
<% provide(:title, "All the kittehs") %>

<ul>
  <h3>All teh kittehs</h3>
  <br><%= link_to "Make a new fluff monster", new_kitten_path %><br><br>

  <%= will_paginate %>

  <% @kittens.each do |kitten| %>
    <ul>
      <%= link_to "Lookie at #{kitten.name}!", kitten, method: :get %>
      <%= link_to "(delete this snuggler)", kitten, method: :delete,
          data: { confirm: "Sure you want to delete this precious baby?" } %>
    </ul><br>
  <% end %>

  <%= will_paginate %>
</ul>

app/views/kittens/new.html.erb
<% provide(:title, "Kreate a new kitteh") %>
<% provide(:button_text, "Kitten!") %>

<ul><h3>Kreate a new kitteh</h3></ul>
<%= render 'form' %>

app/views/kittens/show.html.erb
<% provide(:title, @kitten) %>

<ul>
  <br><h3><%= "#{@kitten.name}" %></h3>
  <%= "Age: #{@kitten.age} months" %>
  <br><%= "Cuteness factor (1-10 scale): #{@kitten.cuteness}" %>
  <br><%= "Softness factor (1-10 scale): #{@kitten.softness}" %><br><br>
  <ul><%= link_to "edit this sweet woogums", edit_kitten_path(@kitten) %></ul>
  <ul>
    <%= link_to "delete this baby darling (how could you)",
        @kitten, method: :delete, data:
        { confirm: "Sure you want to delete this precious meeper?" } %>
  </ul>
  <ul><%= link_to "safely return to kitteh snuggle home", root_url %></ul>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>